// backend/src/seeds/pgcPymes.js
// Plan General Contable PYMES (RD 1514/2007)
// ~280 cuentas predefinidas para PYMES españolas

/**
 * Devuelve el array de cuentas PGC PYMES predefinidas.
 * Cada cuenta tiene: codigo, nombre, tipo, grupo, subgrupo, nivel, padre_codigo
 *
 * Tipos: activo, pasivo, patrimonio, ingreso, gasto
 * Grupos: 1-Financiación básica, 2-Inmovilizado, 3-Existencias,
 *         4-Acreedores/deudores, 5-Cuentas financieras, 6-Compras/gastos, 7-Ventas/ingresos
 * Niveles: 1=grupo, 2=subgrupo, 3=cuenta, 4=subcuenta
 */
export function getPgcPymesCuentas() {
  return [
    // =============================================
    // GRUPO 1: FINANCIACIÓN BÁSICA
    // =============================================
    { codigo: "1", nombre: "Financiación básica", tipo: "patrimonio", grupo: 1, subgrupo: null, nivel: 1, padre_codigo: null },
    { codigo: "10", nombre: "Capital", tipo: "patrimonio", grupo: 1, subgrupo: 10, nivel: 2, padre_codigo: "1" },
    { codigo: "100", nombre: "Capital social", tipo: "patrimonio", grupo: 1, subgrupo: 10, nivel: 3, padre_codigo: "10" },
    { codigo: "101", nombre: "Fondo social", tipo: "patrimonio", grupo: 1, subgrupo: 10, nivel: 3, padre_codigo: "10" },
    { codigo: "102", nombre: "Capital", tipo: "patrimonio", grupo: 1, subgrupo: 10, nivel: 3, padre_codigo: "10" },
    { codigo: "11", nombre: "Reservas", tipo: "patrimonio", grupo: 1, subgrupo: 11, nivel: 2, padre_codigo: "1" },
    { codigo: "112", nombre: "Reserva legal", tipo: "patrimonio", grupo: 1, subgrupo: 11, nivel: 3, padre_codigo: "11" },
    { codigo: "113", nombre: "Reservas voluntarias", tipo: "patrimonio", grupo: 1, subgrupo: 11, nivel: 3, padre_codigo: "11" },
    { codigo: "118", nombre: "Aportaciones de socios", tipo: "patrimonio", grupo: 1, subgrupo: 11, nivel: 3, padre_codigo: "11" },
    { codigo: "12", nombre: "Resultados pendientes de aplicación", tipo: "patrimonio", grupo: 1, subgrupo: 12, nivel: 2, padre_codigo: "1" },
    { codigo: "120", nombre: "Remanente", tipo: "patrimonio", grupo: 1, subgrupo: 12, nivel: 3, padre_codigo: "12" },
    { codigo: "121", nombre: "Resultados negativos de ejercicios anteriores", tipo: "patrimonio", grupo: 1, subgrupo: 12, nivel: 3, padre_codigo: "12" },
    { codigo: "129", nombre: "Resultado del ejercicio", tipo: "patrimonio", grupo: 1, subgrupo: 12, nivel: 3, padre_codigo: "12" },
    { codigo: "13", nombre: "Subvenciones, donaciones y legados", tipo: "patrimonio", grupo: 1, subgrupo: 13, nivel: 2, padre_codigo: "1" },
    { codigo: "130", nombre: "Subvenciones oficiales de capital", tipo: "patrimonio", grupo: 1, subgrupo: 13, nivel: 3, padre_codigo: "13" },
    { codigo: "131", nombre: "Donaciones y legados de capital", tipo: "patrimonio", grupo: 1, subgrupo: 13, nivel: 3, padre_codigo: "13" },
    { codigo: "14", nombre: "Provisiones", tipo: "pasivo", grupo: 1, subgrupo: 14, nivel: 2, padre_codigo: "1" },
    { codigo: "141", nombre: "Provisión para impuestos", tipo: "pasivo", grupo: 1, subgrupo: 14, nivel: 3, padre_codigo: "14" },
    { codigo: "142", nombre: "Provisión para otras responsabilidades", tipo: "pasivo", grupo: 1, subgrupo: 14, nivel: 3, padre_codigo: "14" },
    { codigo: "143", nombre: "Provisión por desmantelamiento", tipo: "pasivo", grupo: 1, subgrupo: 14, nivel: 3, padre_codigo: "14" },
    { codigo: "15", nombre: "Deudas a largo plazo con características especiales", tipo: "pasivo", grupo: 1, subgrupo: 15, nivel: 2, padre_codigo: "1" },
    { codigo: "16", nombre: "Deudas a largo plazo con partes vinculadas", tipo: "pasivo", grupo: 1, subgrupo: 16, nivel: 2, padre_codigo: "1" },
    { codigo: "160", nombre: "Deudas a LP con entidades de crédito vinculadas", tipo: "pasivo", grupo: 1, subgrupo: 16, nivel: 3, padre_codigo: "16" },
    { codigo: "162", nombre: "Deudas a LP con entidades de crédito del grupo", tipo: "pasivo", grupo: 1, subgrupo: 16, nivel: 3, padre_codigo: "16" },
    { codigo: "17", nombre: "Deudas a largo plazo", tipo: "pasivo", grupo: 1, subgrupo: 17, nivel: 2, padre_codigo: "1" },
    { codigo: "170", nombre: "Deudas a LP con entidades de crédito", tipo: "pasivo", grupo: 1, subgrupo: 17, nivel: 3, padre_codigo: "17" },
    { codigo: "171", nombre: "Deudas a LP", tipo: "pasivo", grupo: 1, subgrupo: 17, nivel: 3, padre_codigo: "17" },
    { codigo: "173", nombre: "Proveedores de inmovilizado a LP", tipo: "pasivo", grupo: 1, subgrupo: 17, nivel: 3, padre_codigo: "17" },
    { codigo: "174", nombre: "Acreedores por arrendamiento financiero a LP", tipo: "pasivo", grupo: 1, subgrupo: 17, nivel: 3, padre_codigo: "17" },
    { codigo: "175", nombre: "Efectos a pagar a LP", tipo: "pasivo", grupo: 1, subgrupo: 17, nivel: 3, padre_codigo: "17" },
    { codigo: "176", nombre: "Pasivos por derivados financieros a LP", tipo: "pasivo", grupo: 1, subgrupo: 17, nivel: 3, padre_codigo: "17" },
    { codigo: "18", nombre: "Pasivos por fianzas y garantías a LP", tipo: "pasivo", grupo: 1, subgrupo: 18, nivel: 2, padre_codigo: "1" },
    { codigo: "180", nombre: "Fianzas recibidas a LP", tipo: "pasivo", grupo: 1, subgrupo: 18, nivel: 3, padre_codigo: "18" },
    { codigo: "185", nombre: "Depósitos recibidos a LP", tipo: "pasivo", grupo: 1, subgrupo: 18, nivel: 3, padre_codigo: "18" },

    // =============================================
    // GRUPO 2: INMOVILIZADO
    // =============================================
    { codigo: "2", nombre: "Inmovilizado", tipo: "activo", grupo: 2, subgrupo: null, nivel: 1, padre_codigo: null },
    { codigo: "20", nombre: "Inmovilizaciones intangibles", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 2, padre_codigo: "2" },
    { codigo: "200", nombre: "Investigación", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 3, padre_codigo: "20" },
    { codigo: "201", nombre: "Desarrollo", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 3, padre_codigo: "20" },
    { codigo: "202", nombre: "Concesiones administrativas", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 3, padre_codigo: "20" },
    { codigo: "203", nombre: "Propiedad industrial", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 3, padre_codigo: "20" },
    { codigo: "204", nombre: "Fondo de comercio", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 3, padre_codigo: "20" },
    { codigo: "205", nombre: "Derechos de traspaso", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 3, padre_codigo: "20" },
    { codigo: "206", nombre: "Aplicaciones informáticas", tipo: "activo", grupo: 2, subgrupo: 20, nivel: 3, padre_codigo: "20" },
    { codigo: "21", nombre: "Inmovilizaciones materiales", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 2, padre_codigo: "2" },
    { codigo: "210", nombre: "Terrenos y bienes naturales", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "211", nombre: "Construcciones", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "212", nombre: "Instalaciones técnicas", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "213", nombre: "Maquinaria", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "214", nombre: "Utillaje", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "215", nombre: "Otras instalaciones", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "216", nombre: "Mobiliario", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "217", nombre: "Equipos para procesos de información", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "218", nombre: "Elementos de transporte", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "219", nombre: "Otro inmovilizado material", tipo: "activo", grupo: 2, subgrupo: 21, nivel: 3, padre_codigo: "21" },
    { codigo: "22", nombre: "Inversiones inmobiliarias", tipo: "activo", grupo: 2, subgrupo: 22, nivel: 2, padre_codigo: "2" },
    { codigo: "220", nombre: "Inversiones en terrenos y bienes naturales", tipo: "activo", grupo: 2, subgrupo: 22, nivel: 3, padre_codigo: "22" },
    { codigo: "221", nombre: "Inversiones en construcciones", tipo: "activo", grupo: 2, subgrupo: 22, nivel: 3, padre_codigo: "22" },
    { codigo: "23", nombre: "Inmovilizaciones materiales en curso", tipo: "activo", grupo: 2, subgrupo: 23, nivel: 2, padre_codigo: "2" },
    { codigo: "230", nombre: "Adaptación de terrenos y bienes naturales", tipo: "activo", grupo: 2, subgrupo: 23, nivel: 3, padre_codigo: "23" },
    { codigo: "231", nombre: "Construcciones en curso", tipo: "activo", grupo: 2, subgrupo: 23, nivel: 3, padre_codigo: "23" },
    { codigo: "232", nombre: "Instalaciones técnicas en montaje", tipo: "activo", grupo: 2, subgrupo: 23, nivel: 3, padre_codigo: "23" },
    { codigo: "233", nombre: "Maquinaria en montaje", tipo: "activo", grupo: 2, subgrupo: 23, nivel: 3, padre_codigo: "23" },
    { codigo: "24", nombre: "Inversiones financieras a LP en partes vinculadas", tipo: "activo", grupo: 2, subgrupo: 24, nivel: 2, padre_codigo: "2" },
    { codigo: "240", nombre: "Participaciones a LP en partes vinculadas", tipo: "activo", grupo: 2, subgrupo: 24, nivel: 3, padre_codigo: "24" },
    { codigo: "242", nombre: "Créditos a LP a partes vinculadas", tipo: "activo", grupo: 2, subgrupo: 24, nivel: 3, padre_codigo: "24" },
    { codigo: "25", nombre: "Otras inversiones financieras a LP", tipo: "activo", grupo: 2, subgrupo: 25, nivel: 2, padre_codigo: "2" },
    { codigo: "250", nombre: "Inversiones financieras a LP en instrumentos de patrimonio", tipo: "activo", grupo: 2, subgrupo: 25, nivel: 3, padre_codigo: "25" },
    { codigo: "251", nombre: "Valores representativos de deuda a LP", tipo: "activo", grupo: 2, subgrupo: 25, nivel: 3, padre_codigo: "25" },
    { codigo: "252", nombre: "Créditos a LP", tipo: "activo", grupo: 2, subgrupo: 25, nivel: 3, padre_codigo: "25" },
    { codigo: "253", nombre: "Créditos a LP por enajenación de inmovilizado", tipo: "activo", grupo: 2, subgrupo: 25, nivel: 3, padre_codigo: "25" },
    { codigo: "258", nombre: "Imposiciones a LP", tipo: "activo", grupo: 2, subgrupo: 25, nivel: 3, padre_codigo: "25" },
    { codigo: "26", nombre: "Fianzas y depósitos constituidos a LP", tipo: "activo", grupo: 2, subgrupo: 26, nivel: 2, padre_codigo: "2" },
    { codigo: "260", nombre: "Fianzas constituidas a LP", tipo: "activo", grupo: 2, subgrupo: 26, nivel: 3, padre_codigo: "26" },
    { codigo: "265", nombre: "Depósitos constituidos a LP", tipo: "activo", grupo: 2, subgrupo: 26, nivel: 3, padre_codigo: "26" },
    { codigo: "28", nombre: "Amortización acumulada del inmovilizado", tipo: "activo", grupo: 2, subgrupo: 28, nivel: 2, padre_codigo: "2" },
    { codigo: "280", nombre: "Amortización acumulada del inmovilizado intangible", tipo: "activo", grupo: 2, subgrupo: 28, nivel: 3, padre_codigo: "28" },
    { codigo: "281", nombre: "Amortización acumulada del inmovilizado material", tipo: "activo", grupo: 2, subgrupo: 28, nivel: 3, padre_codigo: "28" },
    { codigo: "282", nombre: "Amortización acumulada de inversiones inmobiliarias", tipo: "activo", grupo: 2, subgrupo: 28, nivel: 3, padre_codigo: "28" },
    { codigo: "29", nombre: "Deterioro de valor del inmovilizado", tipo: "activo", grupo: 2, subgrupo: 29, nivel: 2, padre_codigo: "2" },
    { codigo: "290", nombre: "Deterioro de valor del inmovilizado intangible", tipo: "activo", grupo: 2, subgrupo: 29, nivel: 3, padre_codigo: "29" },
    { codigo: "291", nombre: "Deterioro de valor del inmovilizado material", tipo: "activo", grupo: 2, subgrupo: 29, nivel: 3, padre_codigo: "29" },
    { codigo: "292", nombre: "Deterioro de valor de inversiones inmobiliarias", tipo: "activo", grupo: 2, subgrupo: 29, nivel: 3, padre_codigo: "29" },

    // =============================================
    // GRUPO 3: EXISTENCIAS
    // =============================================
    { codigo: "3", nombre: "Existencias", tipo: "activo", grupo: 3, subgrupo: null, nivel: 1, padre_codigo: null },
    { codigo: "30", nombre: "Comerciales", tipo: "activo", grupo: 3, subgrupo: 30, nivel: 2, padre_codigo: "3" },
    { codigo: "300", nombre: "Mercaderías A", tipo: "activo", grupo: 3, subgrupo: 30, nivel: 3, padre_codigo: "30" },
    { codigo: "31", nombre: "Materias primas", tipo: "activo", grupo: 3, subgrupo: 31, nivel: 2, padre_codigo: "3" },
    { codigo: "310", nombre: "Materias primas A", tipo: "activo", grupo: 3, subgrupo: 31, nivel: 3, padre_codigo: "31" },
    { codigo: "32", nombre: "Otros aprovisionamientos", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 2, padre_codigo: "3" },
    { codigo: "320", nombre: "Elementos y conjuntos incorporables", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 3, padre_codigo: "32" },
    { codigo: "321", nombre: "Combustibles", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 3, padre_codigo: "32" },
    { codigo: "322", nombre: "Repuestos", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 3, padre_codigo: "32" },
    { codigo: "325", nombre: "Materiales diversos", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 3, padre_codigo: "32" },
    { codigo: "326", nombre: "Embalajes", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 3, padre_codigo: "32" },
    { codigo: "327", nombre: "Envases", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 3, padre_codigo: "32" },
    { codigo: "328", nombre: "Material de oficina", tipo: "activo", grupo: 3, subgrupo: 32, nivel: 3, padre_codigo: "32" },
    { codigo: "33", nombre: "Productos en curso", tipo: "activo", grupo: 3, subgrupo: 33, nivel: 2, padre_codigo: "3" },
    { codigo: "330", nombre: "Productos en curso A", tipo: "activo", grupo: 3, subgrupo: 33, nivel: 3, padre_codigo: "33" },
    { codigo: "34", nombre: "Productos semiterminados", tipo: "activo", grupo: 3, subgrupo: 34, nivel: 2, padre_codigo: "3" },
    { codigo: "340", nombre: "Productos semiterminados A", tipo: "activo", grupo: 3, subgrupo: 34, nivel: 3, padre_codigo: "34" },
    { codigo: "35", nombre: "Productos terminados", tipo: "activo", grupo: 3, subgrupo: 35, nivel: 2, padre_codigo: "3" },
    { codigo: "350", nombre: "Productos terminados A", tipo: "activo", grupo: 3, subgrupo: 35, nivel: 3, padre_codigo: "35" },
    { codigo: "36", nombre: "Subproductos, residuos y materiales recuperados", tipo: "activo", grupo: 3, subgrupo: 36, nivel: 2, padre_codigo: "3" },
    { codigo: "39", nombre: "Deterioro de valor de las existencias", tipo: "activo", grupo: 3, subgrupo: 39, nivel: 2, padre_codigo: "3" },
    { codigo: "390", nombre: "Deterioro de valor de mercaderías", tipo: "activo", grupo: 3, subgrupo: 39, nivel: 3, padre_codigo: "39" },
    { codigo: "391", nombre: "Deterioro de valor de materias primas", tipo: "activo", grupo: 3, subgrupo: 39, nivel: 3, padre_codigo: "39" },
    { codigo: "392", nombre: "Deterioro de valor de otros aprovisionamientos", tipo: "activo", grupo: 3, subgrupo: 39, nivel: 3, padre_codigo: "39" },
    { codigo: "395", nombre: "Deterioro de valor de productos terminados", tipo: "activo", grupo: 3, subgrupo: 39, nivel: 3, padre_codigo: "39" },

    // =============================================
    // GRUPO 4: ACREEDORES Y DEUDORES POR OPERACIONES COMERCIALES
    // =============================================
    { codigo: "4", nombre: "Acreedores y deudores por operaciones comerciales", tipo: "activo", grupo: 4, subgrupo: null, nivel: 1, padre_codigo: null },
    { codigo: "40", nombre: "Proveedores", tipo: "pasivo", grupo: 4, subgrupo: 40, nivel: 2, padre_codigo: "4" },
    { codigo: "400", nombre: "Proveedores", tipo: "pasivo", grupo: 4, subgrupo: 40, nivel: 3, padre_codigo: "40" },
    { codigo: "401", nombre: "Proveedores, efectos comerciales a pagar", tipo: "pasivo", grupo: 4, subgrupo: 40, nivel: 3, padre_codigo: "40" },
    { codigo: "403", nombre: "Proveedores, empresas del grupo", tipo: "pasivo", grupo: 4, subgrupo: 40, nivel: 3, padre_codigo: "40" },
    { codigo: "406", nombre: "Envases y embalajes a devolver a proveedores", tipo: "activo", grupo: 4, subgrupo: 40, nivel: 3, padre_codigo: "40" },
    { codigo: "407", nombre: "Anticipos a proveedores", tipo: "activo", grupo: 4, subgrupo: 40, nivel: 3, padre_codigo: "40" },
    { codigo: "41", nombre: "Acreedores varios", tipo: "pasivo", grupo: 4, subgrupo: 41, nivel: 2, padre_codigo: "4" },
    { codigo: "410", nombre: "Acreedores por prestaciones de servicios", tipo: "pasivo", grupo: 4, subgrupo: 41, nivel: 3, padre_codigo: "41" },
    { codigo: "411", nombre: "Acreedores, efectos comerciales a pagar", tipo: "pasivo", grupo: 4, subgrupo: 41, nivel: 3, padre_codigo: "41" },
    { codigo: "43", nombre: "Clientes", tipo: "activo", grupo: 4, subgrupo: 43, nivel: 2, padre_codigo: "4" },
    { codigo: "430", nombre: "Clientes", tipo: "activo", grupo: 4, subgrupo: 43, nivel: 3, padre_codigo: "43" },
    { codigo: "431", nombre: "Clientes, efectos comerciales a cobrar", tipo: "activo", grupo: 4, subgrupo: 43, nivel: 3, padre_codigo: "43" },
    { codigo: "432", nombre: "Clientes, operaciones de factoring", tipo: "activo", grupo: 4, subgrupo: 43, nivel: 3, padre_codigo: "43" },
    { codigo: "433", nombre: "Clientes, empresas del grupo", tipo: "activo", grupo: 4, subgrupo: 43, nivel: 3, padre_codigo: "43" },
    { codigo: "435", nombre: "Clientes de dudoso cobro", tipo: "activo", grupo: 4, subgrupo: 43, nivel: 3, padre_codigo: "43" },
    { codigo: "436", nombre: "Envases y embalajes a devolver por clientes", tipo: "activo", grupo: 4, subgrupo: 43, nivel: 3, padre_codigo: "43" },
    { codigo: "437", nombre: "Anticipos de clientes", tipo: "pasivo", grupo: 4, subgrupo: 43, nivel: 3, padre_codigo: "43" },
    { codigo: "44", nombre: "Deudores varios", tipo: "activo", grupo: 4, subgrupo: 44, nivel: 2, padre_codigo: "4" },
    { codigo: "440", nombre: "Deudores", tipo: "activo", grupo: 4, subgrupo: 44, nivel: 3, padre_codigo: "44" },
    { codigo: "441", nombre: "Deudores, efectos comerciales a cobrar", tipo: "activo", grupo: 4, subgrupo: 44, nivel: 3, padre_codigo: "44" },
    { codigo: "446", nombre: "Deudores de dudoso cobro", tipo: "activo", grupo: 4, subgrupo: 44, nivel: 3, padre_codigo: "44" },
    { codigo: "46", nombre: "Personal", tipo: "pasivo", grupo: 4, subgrupo: 46, nivel: 2, padre_codigo: "4" },
    { codigo: "460", nombre: "Anticipos de remuneraciones", tipo: "activo", grupo: 4, subgrupo: 46, nivel: 3, padre_codigo: "46" },
    { codigo: "465", nombre: "Remuneraciones pendientes de pago", tipo: "pasivo", grupo: 4, subgrupo: 46, nivel: 3, padre_codigo: "46" },
    { codigo: "466", nombre: "Remuneraciones mediante sistemas de aportación definida pendientes de pago", tipo: "pasivo", grupo: 4, subgrupo: 46, nivel: 3, padre_codigo: "46" },
    { codigo: "47", nombre: "Administraciones Públicas", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 2, padre_codigo: "4" },
    { codigo: "470", nombre: "Hacienda Pública, deudora por diversos conceptos", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "4700", nombre: "HP deudora por IVA", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 4, padre_codigo: "470" },
    { codigo: "4708", nombre: "HP deudora por subvenciones concedidas", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 4, padre_codigo: "470" },
    { codigo: "4709", nombre: "HP deudora por devolución de impuestos", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 4, padre_codigo: "470" },
    { codigo: "471", nombre: "Organismos de la Seguridad Social, deudores", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "472", nombre: "Hacienda Pública, IVA soportado", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "473", nombre: "Hacienda Pública, retenciones y pagos a cuenta", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "474", nombre: "Activos por impuesto diferido", tipo: "activo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "475", nombre: "Hacienda Pública, acreedora por conceptos fiscales", tipo: "pasivo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "4750", nombre: "HP acreedora por IVA", tipo: "pasivo", grupo: 4, subgrupo: 47, nivel: 4, padre_codigo: "475" },
    { codigo: "4751", nombre: "HP acreedora por retenciones practicadas", tipo: "pasivo", grupo: 4, subgrupo: 47, nivel: 4, padre_codigo: "475" },
    { codigo: "4752", nombre: "HP acreedora por Impuesto sobre Sociedades", tipo: "pasivo", grupo: 4, subgrupo: 47, nivel: 4, padre_codigo: "475" },
    { codigo: "476", nombre: "Organismos de la Seguridad Social, acreedores", tipo: "pasivo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "477", nombre: "Hacienda Pública, IVA repercutido", tipo: "pasivo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "479", nombre: "Pasivos por diferencias temporarias imponibles", tipo: "pasivo", grupo: 4, subgrupo: 47, nivel: 3, padre_codigo: "47" },
    { codigo: "48", nombre: "Ajustes por periodificación", tipo: "activo", grupo: 4, subgrupo: 48, nivel: 2, padre_codigo: "4" },
    { codigo: "480", nombre: "Gastos anticipados", tipo: "activo", grupo: 4, subgrupo: 48, nivel: 3, padre_codigo: "48" },
    { codigo: "485", nombre: "Ingresos anticipados", tipo: "pasivo", grupo: 4, subgrupo: 48, nivel: 3, padre_codigo: "48" },
    { codigo: "49", nombre: "Deterioro de valor de créditos comerciales", tipo: "activo", grupo: 4, subgrupo: 49, nivel: 2, padre_codigo: "4" },
    { codigo: "490", nombre: "Deterioro de valor de créditos por operaciones comerciales", tipo: "activo", grupo: 4, subgrupo: 49, nivel: 3, padre_codigo: "49" },
    { codigo: "493", nombre: "Deterioro de valor de créditos por operaciones comerciales con partes vinculadas", tipo: "activo", grupo: 4, subgrupo: 49, nivel: 3, padre_codigo: "49" },

    // =============================================
    // GRUPO 5: CUENTAS FINANCIERAS
    // =============================================
    { codigo: "5", nombre: "Cuentas financieras", tipo: "activo", grupo: 5, subgrupo: null, nivel: 1, padre_codigo: null },
    { codigo: "50", nombre: "Empréstitos y deudas a CP con partes vinculadas", tipo: "pasivo", grupo: 5, subgrupo: 50, nivel: 2, padre_codigo: "5" },
    { codigo: "500", nombre: "Obligaciones y bonos a CP", tipo: "pasivo", grupo: 5, subgrupo: 50, nivel: 3, padre_codigo: "50" },
    { codigo: "51", nombre: "Deudas a CP con partes vinculadas", tipo: "pasivo", grupo: 5, subgrupo: 51, nivel: 2, padre_codigo: "5" },
    { codigo: "510", nombre: "Deudas a CP con entidades de crédito vinculadas", tipo: "pasivo", grupo: 5, subgrupo: 51, nivel: 3, padre_codigo: "51" },
    { codigo: "512", nombre: "Deudas a CP con entidades de crédito del grupo", tipo: "pasivo", grupo: 5, subgrupo: 51, nivel: 3, padre_codigo: "51" },
    { codigo: "52", nombre: "Deudas a CP por préstamos recibidos", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 2, padre_codigo: "5" },
    { codigo: "520", nombre: "Deudas a CP con entidades de crédito", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "521", nombre: "Deudas a CP", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "523", nombre: "Proveedores de inmovilizado a CP", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "524", nombre: "Acreedores por arrendamiento financiero a CP", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "525", nombre: "Efectos a pagar a CP", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "526", nombre: "Dividendo activo a pagar", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "527", nombre: "Intereses a CP de deudas con partes vinculadas", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "528", nombre: "Intereses a CP de deudas", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "529", nombre: "Provisiones a CP", tipo: "pasivo", grupo: 5, subgrupo: 52, nivel: 3, padre_codigo: "52" },
    { codigo: "53", nombre: "Inversiones financieras a CP en partes vinculadas", tipo: "activo", grupo: 5, subgrupo: 53, nivel: 2, padre_codigo: "5" },
    { codigo: "530", nombre: "Participaciones a CP en partes vinculadas", tipo: "activo", grupo: 5, subgrupo: 53, nivel: 3, padre_codigo: "53" },
    { codigo: "532", nombre: "Créditos a CP a partes vinculadas", tipo: "activo", grupo: 5, subgrupo: 53, nivel: 3, padre_codigo: "53" },
    { codigo: "54", nombre: "Otras inversiones financieras a CP", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 2, padre_codigo: "5" },
    { codigo: "540", nombre: "Inversiones financieras a CP en instrumentos de patrimonio", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "541", nombre: "Valores representativos de deuda a CP", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "542", nombre: "Créditos a CP", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "543", nombre: "Créditos a CP por enajenación de inmovilizado", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "545", nombre: "Dividendo a cobrar", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "546", nombre: "Intereses a CP de valores representativos de deuda", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "547", nombre: "Intereses a CP de créditos", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "548", nombre: "Imposiciones a CP", tipo: "activo", grupo: 5, subgrupo: 54, nivel: 3, padre_codigo: "54" },
    { codigo: "55", nombre: "Otras cuentas no bancarias", tipo: "activo", grupo: 5, subgrupo: 55, nivel: 2, padre_codigo: "5" },
    { codigo: "550", nombre: "Titular de la explotación", tipo: "activo", grupo: 5, subgrupo: 55, nivel: 3, padre_codigo: "55" },
    { codigo: "551", nombre: "Cuenta corriente con socios y administradores", tipo: "activo", grupo: 5, subgrupo: 55, nivel: 3, padre_codigo: "55" },
    { codigo: "555", nombre: "Partidas pendientes de aplicación", tipo: "activo", grupo: 5, subgrupo: 55, nivel: 3, padre_codigo: "55" },
    { codigo: "56", nombre: "Fianzas y depósitos recibidos y constituidos a CP", tipo: "activo", grupo: 5, subgrupo: 56, nivel: 2, padre_codigo: "5" },
    { codigo: "560", nombre: "Fianzas recibidas a CP", tipo: "pasivo", grupo: 5, subgrupo: 56, nivel: 3, padre_codigo: "56" },
    { codigo: "561", nombre: "Depósitos recibidos a CP", tipo: "pasivo", grupo: 5, subgrupo: 56, nivel: 3, padre_codigo: "56" },
    { codigo: "565", nombre: "Fianzas constituidas a CP", tipo: "activo", grupo: 5, subgrupo: 56, nivel: 3, padre_codigo: "56" },
    { codigo: "566", nombre: "Depósitos constituidos a CP", tipo: "activo", grupo: 5, subgrupo: 56, nivel: 3, padre_codigo: "56" },
    { codigo: "57", nombre: "Tesorería", tipo: "activo", grupo: 5, subgrupo: 57, nivel: 2, padre_codigo: "5" },
    { codigo: "570", nombre: "Caja, euros", tipo: "activo", grupo: 5, subgrupo: 57, nivel: 3, padre_codigo: "57" },
    { codigo: "571", nombre: "Caja, moneda extranjera", tipo: "activo", grupo: 5, subgrupo: 57, nivel: 3, padre_codigo: "57" },
    { codigo: "572", nombre: "Bancos e instituciones de crédito c/c vista, euros", tipo: "activo", grupo: 5, subgrupo: 57, nivel: 3, padre_codigo: "57" },
    { codigo: "573", nombre: "Bancos e instituciones de crédito c/c vista, moneda extranjera", tipo: "activo", grupo: 5, subgrupo: 57, nivel: 3, padre_codigo: "57" },
    { codigo: "574", nombre: "Bancos e instituciones de crédito, cuentas de ahorro, euros", tipo: "activo", grupo: 5, subgrupo: 57, nivel: 3, padre_codigo: "57" },
    { codigo: "59", nombre: "Deterioro del valor de inversiones financieras a CP", tipo: "activo", grupo: 5, subgrupo: 59, nivel: 2, padre_codigo: "5" },
    { codigo: "593", nombre: "Deterioro de valor de participaciones a CP en partes vinculadas", tipo: "activo", grupo: 5, subgrupo: 59, nivel: 3, padre_codigo: "59" },
    { codigo: "597", nombre: "Deterioro de valor de valores representativos de deuda a CP", tipo: "activo", grupo: 5, subgrupo: 59, nivel: 3, padre_codigo: "59" },
    { codigo: "598", nombre: "Deterioro de valor de créditos a CP", tipo: "activo", grupo: 5, subgrupo: 59, nivel: 3, padre_codigo: "59" },

    // =============================================
    // GRUPO 6: COMPRAS Y GASTOS
    // =============================================
    { codigo: "6", nombre: "Compras y gastos", tipo: "gasto", grupo: 6, subgrupo: null, nivel: 1, padre_codigo: null },
    { codigo: "60", nombre: "Compras", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 2, padre_codigo: "6" },
    { codigo: "600", nombre: "Compras de mercaderías", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 3, padre_codigo: "60" },
    { codigo: "601", nombre: "Compras de materias primas", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 3, padre_codigo: "60" },
    { codigo: "602", nombre: "Compras de otros aprovisionamientos", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 3, padre_codigo: "60" },
    { codigo: "606", nombre: "Descuentos sobre compras por pronto pago", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 3, padre_codigo: "60" },
    { codigo: "607", nombre: "Trabajos realizados por otras empresas", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 3, padre_codigo: "60" },
    { codigo: "608", nombre: "Devoluciones de compras y operaciones similares", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 3, padre_codigo: "60" },
    { codigo: "609", nombre: "Rappels por compras", tipo: "gasto", grupo: 6, subgrupo: 60, nivel: 3, padre_codigo: "60" },
    { codigo: "61", nombre: "Variación de existencias", tipo: "gasto", grupo: 6, subgrupo: 61, nivel: 2, padre_codigo: "6" },
    { codigo: "610", nombre: "Variación de existencias de mercaderías", tipo: "gasto", grupo: 6, subgrupo: 61, nivel: 3, padre_codigo: "61" },
    { codigo: "611", nombre: "Variación de existencias de materias primas", tipo: "gasto", grupo: 6, subgrupo: 61, nivel: 3, padre_codigo: "61" },
    { codigo: "612", nombre: "Variación de existencias de otros aprovisionamientos", tipo: "gasto", grupo: 6, subgrupo: 61, nivel: 3, padre_codigo: "61" },
    { codigo: "62", nombre: "Servicios exteriores", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 2, padre_codigo: "6" },
    { codigo: "620", nombre: "Gastos en investigación y desarrollo del ejercicio", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "621", nombre: "Arrendamientos y cánones", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "622", nombre: "Reparaciones y conservación", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "623", nombre: "Servicios de profesionales independientes", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "624", nombre: "Transportes", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "625", nombre: "Primas de seguros", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "626", nombre: "Servicios bancarios y similares", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "627", nombre: "Publicidad, propaganda y relaciones públicas", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "628", nombre: "Suministros", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "629", nombre: "Otros servicios", tipo: "gasto", grupo: 6, subgrupo: 62, nivel: 3, padre_codigo: "62" },
    { codigo: "63", nombre: "Tributos", tipo: "gasto", grupo: 6, subgrupo: 63, nivel: 2, padre_codigo: "6" },
    { codigo: "630", nombre: "Impuesto sobre beneficios", tipo: "gasto", grupo: 6, subgrupo: 63, nivel: 3, padre_codigo: "63" },
    { codigo: "631", nombre: "Otros tributos", tipo: "gasto", grupo: 6, subgrupo: 63, nivel: 3, padre_codigo: "63" },
    { codigo: "633", nombre: "Ajustes negativos en la imposición sobre beneficios", tipo: "gasto", grupo: 6, subgrupo: 63, nivel: 3, padre_codigo: "63" },
    { codigo: "634", nombre: "Ajustes negativos en la imposición indirecta", tipo: "gasto", grupo: 6, subgrupo: 63, nivel: 3, padre_codigo: "63" },
    { codigo: "636", nombre: "Devolución de impuestos", tipo: "gasto", grupo: 6, subgrupo: 63, nivel: 3, padre_codigo: "63" },
    { codigo: "64", nombre: "Gastos de personal", tipo: "gasto", grupo: 6, subgrupo: 64, nivel: 2, padre_codigo: "6" },
    { codigo: "640", nombre: "Sueldos y salarios", tipo: "gasto", grupo: 6, subgrupo: 64, nivel: 3, padre_codigo: "64" },
    { codigo: "641", nombre: "Indemnizaciones", tipo: "gasto", grupo: 6, subgrupo: 64, nivel: 3, padre_codigo: "64" },
    { codigo: "642", nombre: "Seguridad Social a cargo de la empresa", tipo: "gasto", grupo: 6, subgrupo: 64, nivel: 3, padre_codigo: "64" },
    { codigo: "649", nombre: "Otros gastos sociales", tipo: "gasto", grupo: 6, subgrupo: 64, nivel: 3, padre_codigo: "64" },
    { codigo: "65", nombre: "Otros gastos de gestión", tipo: "gasto", grupo: 6, subgrupo: 65, nivel: 2, padre_codigo: "6" },
    { codigo: "650", nombre: "Pérdidas de créditos comerciales incobrables", tipo: "gasto", grupo: 6, subgrupo: 65, nivel: 3, padre_codigo: "65" },
    { codigo: "651", nombre: "Resultados de operaciones en común", tipo: "gasto", grupo: 6, subgrupo: 65, nivel: 3, padre_codigo: "65" },
    { codigo: "659", nombre: "Otras pérdidas en gestión corriente", tipo: "gasto", grupo: 6, subgrupo: 65, nivel: 3, padre_codigo: "65" },
    { codigo: "66", nombre: "Gastos financieros", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 2, padre_codigo: "6" },
    { codigo: "660", nombre: "Gastos financieros por actualización de provisiones", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "661", nombre: "Intereses de obligaciones y bonos", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "662", nombre: "Intereses de deudas", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "663", nombre: "Pérdidas por valoración de instrumentos financieros", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "665", nombre: "Intereses por descuento de efectos y operaciones de factoring", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "666", nombre: "Pérdidas en participaciones y valores representativos de deuda", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "667", nombre: "Pérdidas de créditos no comerciales", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "668", nombre: "Diferencias negativas de cambio", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "669", nombre: "Otros gastos financieros", tipo: "gasto", grupo: 6, subgrupo: 66, nivel: 3, padre_codigo: "66" },
    { codigo: "67", nombre: "Pérdidas procedentes de activos no corrientes y gastos excepcionales", tipo: "gasto", grupo: 6, subgrupo: 67, nivel: 2, padre_codigo: "6" },
    { codigo: "670", nombre: "Pérdidas procedentes del inmovilizado intangible", tipo: "gasto", grupo: 6, subgrupo: 67, nivel: 3, padre_codigo: "67" },
    { codigo: "671", nombre: "Pérdidas procedentes del inmovilizado material", tipo: "gasto", grupo: 6, subgrupo: 67, nivel: 3, padre_codigo: "67" },
    { codigo: "672", nombre: "Pérdidas procedentes de las inversiones inmobiliarias", tipo: "gasto", grupo: 6, subgrupo: 67, nivel: 3, padre_codigo: "67" },
    { codigo: "678", nombre: "Gastos excepcionales", tipo: "gasto", grupo: 6, subgrupo: 67, nivel: 3, padre_codigo: "67" },
    { codigo: "68", nombre: "Dotaciones para amortizaciones", tipo: "gasto", grupo: 6, subgrupo: 68, nivel: 2, padre_codigo: "6" },
    { codigo: "680", nombre: "Amortización del inmovilizado intangible", tipo: "gasto", grupo: 6, subgrupo: 68, nivel: 3, padre_codigo: "68" },
    { codigo: "681", nombre: "Amortización del inmovilizado material", tipo: "gasto", grupo: 6, subgrupo: 68, nivel: 3, padre_codigo: "68" },
    { codigo: "682", nombre: "Amortización de las inversiones inmobiliarias", tipo: "gasto", grupo: 6, subgrupo: 68, nivel: 3, padre_codigo: "68" },
    { codigo: "69", nombre: "Pérdidas por deterioro y otras dotaciones", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 2, padre_codigo: "6" },
    { codigo: "690", nombre: "Pérdidas por deterioro del inmovilizado intangible", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "691", nombre: "Pérdidas por deterioro del inmovilizado material", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "692", nombre: "Pérdidas por deterioro de las inversiones inmobiliarias", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "693", nombre: "Pérdidas por deterioro de existencias", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "694", nombre: "Pérdidas por deterioro de créditos por operaciones comerciales", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "695", nombre: "Dotación a la provisión por operaciones comerciales", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "696", nombre: "Pérdidas por deterioro de participaciones y valores representativos de deuda a LP", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "697", nombre: "Pérdidas por deterioro de créditos a LP", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "698", nombre: "Pérdidas por deterioro de participaciones y valores representativos de deuda a CP", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },
    { codigo: "699", nombre: "Pérdidas por deterioro de créditos a CP", tipo: "gasto", grupo: 6, subgrupo: 69, nivel: 3, padre_codigo: "69" },

    // =============================================
    // GRUPO 7: VENTAS E INGRESOS
    // =============================================
    { codigo: "7", nombre: "Ventas e ingresos", tipo: "ingreso", grupo: 7, subgrupo: null, nivel: 1, padre_codigo: null },
    { codigo: "70", nombre: "Ventas de mercaderías, de producción propia, de servicios, etc.", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 2, padre_codigo: "7" },
    { codigo: "700", nombre: "Ventas de mercaderías", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "701", nombre: "Ventas de productos terminados", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "702", nombre: "Ventas de productos semiterminados", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "703", nombre: "Ventas de subproductos y residuos", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "704", nombre: "Ventas de envases y embalajes", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "705", nombre: "Prestaciones de servicios", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "706", nombre: "Descuentos sobre ventas por pronto pago", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "708", nombre: "Devoluciones de ventas y operaciones similares", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "709", nombre: "Rappels sobre ventas", tipo: "ingreso", grupo: 7, subgrupo: 70, nivel: 3, padre_codigo: "70" },
    { codigo: "71", nombre: "Variación de existencias", tipo: "ingreso", grupo: 7, subgrupo: 71, nivel: 2, padre_codigo: "7" },
    { codigo: "710", nombre: "Variación de existencias de productos en curso", tipo: "ingreso", grupo: 7, subgrupo: 71, nivel: 3, padre_codigo: "71" },
    { codigo: "711", nombre: "Variación de existencias de productos semiterminados", tipo: "ingreso", grupo: 7, subgrupo: 71, nivel: 3, padre_codigo: "71" },
    { codigo: "712", nombre: "Variación de existencias de productos terminados", tipo: "ingreso", grupo: 7, subgrupo: 71, nivel: 3, padre_codigo: "71" },
    { codigo: "713", nombre: "Variación de existencias de subproductos, residuos y materiales recuperados", tipo: "ingreso", grupo: 7, subgrupo: 71, nivel: 3, padre_codigo: "71" },
    { codigo: "73", nombre: "Trabajos realizados para la empresa", tipo: "ingreso", grupo: 7, subgrupo: 73, nivel: 2, padre_codigo: "7" },
    { codigo: "730", nombre: "Trabajos realizados para el inmovilizado intangible", tipo: "ingreso", grupo: 7, subgrupo: 73, nivel: 3, padre_codigo: "73" },
    { codigo: "731", nombre: "Trabajos realizados para el inmovilizado material", tipo: "ingreso", grupo: 7, subgrupo: 73, nivel: 3, padre_codigo: "73" },
    { codigo: "733", nombre: "Trabajos realizados para el inmovilizado material en curso", tipo: "ingreso", grupo: 7, subgrupo: 73, nivel: 3, padre_codigo: "73" },
    { codigo: "74", nombre: "Subvenciones, donaciones y legados a la explotación", tipo: "ingreso", grupo: 7, subgrupo: 74, nivel: 2, padre_codigo: "7" },
    { codigo: "740", nombre: "Subvenciones, donaciones y legados a la explotación", tipo: "ingreso", grupo: 7, subgrupo: 74, nivel: 3, padre_codigo: "74" },
    { codigo: "746", nombre: "Subvenciones, donaciones y legados de capital transferidos al resultado del ejercicio", tipo: "ingreso", grupo: 7, subgrupo: 74, nivel: 3, padre_codigo: "74" },
    { codigo: "747", nombre: "Otras subvenciones, donaciones y legados transferidos al resultado del ejercicio", tipo: "ingreso", grupo: 7, subgrupo: 74, nivel: 3, padre_codigo: "74" },
    { codigo: "75", nombre: "Otros ingresos de gestión", tipo: "ingreso", grupo: 7, subgrupo: 75, nivel: 2, padre_codigo: "7" },
    { codigo: "751", nombre: "Resultados de operaciones en común", tipo: "ingreso", grupo: 7, subgrupo: 75, nivel: 3, padre_codigo: "75" },
    { codigo: "752", nombre: "Ingresos por arrendamientos", tipo: "ingreso", grupo: 7, subgrupo: 75, nivel: 3, padre_codigo: "75" },
    { codigo: "753", nombre: "Ingresos de propiedad industrial cedida en explotación", tipo: "ingreso", grupo: 7, subgrupo: 75, nivel: 3, padre_codigo: "75" },
    { codigo: "754", nombre: "Ingresos por comisiones", tipo: "ingreso", grupo: 7, subgrupo: 75, nivel: 3, padre_codigo: "75" },
    { codigo: "755", nombre: "Ingresos por servicios al personal", tipo: "ingreso", grupo: 7, subgrupo: 75, nivel: 3, padre_codigo: "75" },
    { codigo: "759", nombre: "Ingresos por servicios diversos", tipo: "ingreso", grupo: 7, subgrupo: 75, nivel: 3, padre_codigo: "75" },
    { codigo: "76", nombre: "Ingresos financieros", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 2, padre_codigo: "7" },
    { codigo: "760", nombre: "Ingresos de participaciones en instrumentos de patrimonio", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 3, padre_codigo: "76" },
    { codigo: "761", nombre: "Ingresos de valores representativos de deuda", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 3, padre_codigo: "76" },
    { codigo: "762", nombre: "Ingresos de créditos", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 3, padre_codigo: "76" },
    { codigo: "763", nombre: "Beneficios por valoración de instrumentos financieros", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 3, padre_codigo: "76" },
    { codigo: "766", nombre: "Beneficios en participaciones y valores representativos de deuda", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 3, padre_codigo: "76" },
    { codigo: "768", nombre: "Diferencias positivas de cambio", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 3, padre_codigo: "76" },
    { codigo: "769", nombre: "Otros ingresos financieros", tipo: "ingreso", grupo: 7, subgrupo: 76, nivel: 3, padre_codigo: "76" },
    { codigo: "77", nombre: "Beneficios procedentes de activos no corrientes e ingresos excepcionales", tipo: "ingreso", grupo: 7, subgrupo: 77, nivel: 2, padre_codigo: "7" },
    { codigo: "770", nombre: "Beneficios procedentes del inmovilizado intangible", tipo: "ingreso", grupo: 7, subgrupo: 77, nivel: 3, padre_codigo: "77" },
    { codigo: "771", nombre: "Beneficios procedentes del inmovilizado material", tipo: "ingreso", grupo: 7, subgrupo: 77, nivel: 3, padre_codigo: "77" },
    { codigo: "772", nombre: "Beneficios procedentes de las inversiones inmobiliarias", tipo: "ingreso", grupo: 7, subgrupo: 77, nivel: 3, padre_codigo: "77" },
    { codigo: "778", nombre: "Ingresos excepcionales", tipo: "ingreso", grupo: 7, subgrupo: 77, nivel: 3, padre_codigo: "77" },
    { codigo: "79", nombre: "Excesos y aplicaciones de provisiones y de pérdidas por deterioro", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 2, padre_codigo: "7" },
    { codigo: "790", nombre: "Reversión del deterioro del inmovilizado intangible", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "791", nombre: "Reversión del deterioro del inmovilizado material", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "792", nombre: "Reversión del deterioro de las inversiones inmobiliarias", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "793", nombre: "Reversión del deterioro de existencias", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "794", nombre: "Reversión del deterioro de créditos por operaciones comerciales", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "795", nombre: "Exceso de provisiones", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "796", nombre: "Reversión del deterioro de participaciones y valores representativos de deuda a LP", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "797", nombre: "Reversión del deterioro de créditos a LP", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "798", nombre: "Reversión del deterioro de participaciones y valores representativos de deuda a CP", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
    { codigo: "799", nombre: "Reversión del deterioro de créditos a CP", tipo: "ingreso", grupo: 7, subgrupo: 79, nivel: 3, padre_codigo: "79" },
  ];
}
